# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HydroPot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod  'AWSPinpoint'
  pod  'AWSMobileClient'
  # Pods for HydroPot

  target 'HydroPotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HydroPotUITests' do
    # Pods for testing
  end

end
